### ISSUE TITLE
Failing to save dataframe to bigquery

### ISSUE THREAD

**Issue by samelamin** [spotify/spark-bigquery#11]
Hi folks

I am launching a new cluster using Google's dataproc and although using bigQuerySelect works and return results when I try to save those results to a big query table it fails with the below stack trace

Also as a side note, I am packaging my spark application as an "uber" or fat jar with this connector added as a dependency

for some reason when I launch a job with "--packages com.spotify:spark-bigquery_2.10:0.1.0" as an argument, it cant find the dependency when it tries to import the package in the code base

should I pass the --packages somewhere else? 

my code: 

```
    val df = sqlContext.bigQuerySelect( "SELECT *  FROM [bigquery-public-data:hacker_news.comments] LIMIT 1000")
    df.limit(10).show()

    df.limit(10).saveAsBigQueryTabele("projectid:tablename")
```

```
16/08/10 13:00:35 INFO com.databricks.spark.avro.AvroRelation: using deflate: -1 for Avro output

[Stage 5:>                                                          (0 + 1) / 2]
[Stage 5:=============================>                             (1 + 1) / 2]16/08/10 13:00:39 WARN org.apache.spark.scheduler.TaskSetManager: Lost task 0.0 in stage 6.0 (TID 71, cluster-1-w-0.c.justeat-datalake.internal): java.lang.NoSuchMethodError: org.apache.avro.generic.GenericData.createDatumWriter(Lorg/apache/avro/Schema;)Lorg/apache/avro/io/DatumWriter;
    at org.apache.avro.mapreduce.AvroKeyRecordWriter.<init>(AvroKeyRecordWriter.java:55)
    at org.apache.avro.mapreduce.AvroKeyOutputFormat$RecordWriterFactory.create(AvroKeyOutputFormat.java:79)
    at org.apache.avro.mapreduce.AvroKeyOutputFormat.getRecordWriter(AvroKeyOutputFormat.java:105)
    at com.databricks.spark.avro.AvroOutputWriter.<init>(AvroOutputWriter.scala:82)
    at com.databricks.spark.avro.AvroOutputWriterFactory.newInstance(AvroOutputWriterFactory.scala:31)
    at org.apache.spark.sql.execution.datasources.BaseWriterContainer.newOutputWriter(WriterContainer.scala:129)
    at org.apache.spark.sql.execution.datasources.DefaultWriterContainer.writeRows(WriterContainer.scala:255)
    at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1$$anonfun$apply$mcV$sp$3.apply(InsertIntoHadoopFsRelation.scala:148)
    at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1$$anonfun$apply$mcV$sp$3.apply(InsertIntoHadoopFsRelation.scala:148)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

16/08/10 13:00:40 ERROR org.apache.spark.scheduler.cluster.YarnScheduler: Lost executor 1 on cluster-1-w-0.c.justeat-datalake.internal: Container marked as failed: container_1470833273562_0003_01_000002 on host: cluster-1-w-0.c.justeat-datalake.internal. Exit status: 50. Diagnostics: Exception from container-launch.
Container id: container_1470833273562_0003_01_000002
Exit code: 50
Stack trace: ExitCodeException exitCode=50: 
    at org.apache.hadoop.util.Shell.runCommand(Shell.java:545)
    at org.apache.hadoop.util.Shell.run(Shell.java:456)
    at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:722)
    at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:212)
    at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
    at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)


Container exited with a non-zero exit code 50
```

**Comment by nevillelyh** [comment]
`java.lang.NoSuchMethodError: org.apache.avro.generic.GenericData.createDatumWriter(Lorg/apache/avro/Schema;)Lorg/apache/avro/io/DatumWriter;`

Looks related to these:
https://github.com/databricks/spark-redshift/issues/129
https://github.com/databricks/spark-avro/issues/91

I suspect the avro-mapred that came with Dataproc is older than the one in spark-bigquery. Can you try the suggestions in those issues?

**Comment by samelamin** [comment]
ok sure  I will try that 

In the mean time can you suggest how I can pass in the packages so i dont have to bundle up in a far jar?

**Comment by nevillelyh** [comment]
You'll probably face the same issue with or without fat jar since Hadoop comes with an older version of avro-mapred. What's the Hadoop and Spark version you're running?

**Comment by samelamin** [comment]
No I dont think it is, but it would be beneficial to know how to launch it without a fat jar

But It doesnt actually give me an option to choose what version of spark or hadoop to use,  I am just creating a cluster via dataproc. I only get the option to choose the type of job (spark/sparksql/hive) from the job section

**Comment by nevillelyh** [comment]
Do you have the complete command and stack trace of submit?

**Comment by samelamin** [comment]
thats what im trying to find now, seems the logs are stored in google cloud storage but doesnt actually have the submit info

Debugging without a stack trace is really frustrating :( 

I will keep digging, out of interest how do you launch spark submit jobs on dataproc with packages? just via arguments?

**Comment by nevillelyh** [comment]
We use `--packages` when running spark-submit or spark-shell. You mentioned "it cant find the dependency when it tries to import the package in the code base". What was the error message?

**Comment by samelamin** [comment]
sorry it works via the shell, but trying to get it to run from dataproc is failing
ill have to have a look at how i can overwrite the avro package

**Comment by samelamin** [comment]
FYI i think the confusion was because I couldnt run spark-shell since I am uploading a jar

I was able to ssh into a fresh cluster created in Dataproc

and running spark-shell --packages com.spotify:spark-bigquery_2.10:0.1.0 Causes this error too

spark version on the box is 1.6.2 so maybe this package isnt aimed at that, ill try to find a way to specify which avro type I want

Out of interest what sort of spark cluster do you use on dataproc, because you dont get an option to choose what version to run

**Comment by nevillelyh** [comment]
It's under "Image version". Read here: https://cloud.google.com/dataproc/concepts/dataproc-versions

I'm hitting the avro exception too and this seems new. Will look into it.

**Comment by samelamin** [comment]
Phew I thought i was being a complete numpty! 

Alright no worries, ill leave it to you folks

in the mean time is there anything I can do to work around it, like save directly to big query and skip avro?

**Comment by nevillelyh** [comment]
Hadoop is using avro 1.7.4 which is missing the method.
You can probably work around it by monkey replacing the following file with a newer version.
/usr/lib/hadoop/lib/avro-1.7.4.jar

Meanwhile I'll look into nicer ways to circumvent the Hadoop Avro version problem.

**Comment by samelamin** [comment]
I was able to get the job to run by following your advice @nevillelyh  but i also had to remove the avro jar from hadoop-mapreduce as well

Probably should keep the issue open till a cleaner solution is implemented?

To help people in the future here is the bootup script, run this as a init script when the cluster starts up and your good to go! 

``` #!/bin/bash`
# Get Avro jar and copy it into /usr/lib/hadoop-mapreduce
cd /tmp/
wget http://ftp.cuhk.edu.hk/pub/packages/apache.org/avro/avro-1.7.7/java/avro-1.7.7.jar
sudo mkdir -p /usr/lib/hadoop-mapreduce
sudo rm /usr/lib/hadoop-mapreduce/avro-1.7.4
sudo rm /usr/lib/hadoop/lib/avro-1.7.4
sudo cp avro-1.7.7.jar /usr/lib/hadoop-mapreduce
sudo cp avro-1.7.7.jar /usr/lib/hadoop/lib
```
