### ISSUE TITLE
Use with Databricks

### ISSUE THREAD

**Issue by samelamin** [spotify/spark-bigquery#12]
After a quick call with the folks at databricks it seems we cant set environment variables because they are a managed service and you cant edit the environment variables

Is there a way to pass in the credentials? even a path without having the variables themselves set up?

**Comment by nevillelyh** [comment]
You can probably just retrieve the credential file in scala code before setting it via `sqlContext.setGcpJsonKeyFile`?

**Comment by samelamin** [comment]
Yeah I thought I could do that, sadly that call fails immediately because no environment is set even when pointing to the file in the tmp folder 

also on a side note @nevillelyh gotta say the support on this connector is absolutely amazing! you folks are legends!

**Comment by nevillelyh** [comment]
Thanks, appreciate it!

Another possibility is to package HDFS config files inside your jar, in `src/main/resources/core-site.xml`.
See this page: https://cloud.google.com/hadoop/google-cloud-storage-connector

"google.cloud.auth.service.account.keyfile" is the key of interest. Not sure if the file has to be on local FS but you could try.

**Comment by samelamin** [comment]
no need for thanks it had to be said!

Ok i will try that next, but whats cool about databricks is you just type in your code and it runs in the cluster, ideally you want to set up everything in the code and run it as a notebook rather than upload jars

but i know you can upload jars as dependency so maybe that might work. I will keep you updated

**Comment by samelamin** [comment]
One more thing, by editing the core-site.xml wont i have to rebuild the connector?

**Comment by nevillelyh** [comment]
No I mean put it in your job repo. Just make sure it's packaged in the jar.

**Comment by samelamin** [comment]
so if I package it up in a jar using sbt will it overwrite the existing config(if any are available?)

**Comment by nevillelyh** [comment]
Actually it shouldn't be different from overturning interesting overridding with conf.set. You just have to set right ones to make it work.

**Comment by samelamin** [comment]
So if i just edit the conf parameter for the secret key, you reckon that should solve it? without the need to package the jar?

**Comment by nevillelyh** [comment]
You'll have to try :)

**Comment by samelamin** [comment]
ah sadly that didnt work either

its as if theres a check for the environment variable at the very start, and if nothing is set it throws the exception 

oh well ill keep trying

**Comment by samelamin** [comment]
Hi @nevillelyh Hope everything is ok

I failed completely and miserably to get the connector to work on Databricks. They have a security precatiouns to set env variables

Any chance there might be a work around for this? seems like theres an automatic check for the variables and the connector just dies when it cant find it :(

**Comment by nevillelyh** [comment]
Not sure how we can help since we don't use Databricks.
If you just wanna get it to work Databricks for now and don't care about portability, maybe fork the repo and hard code those settings.

I'm guessing you're a paying customer of both Databricks and GCP so I'd escalate to both teams and see if they can work something out. That's a win-win for both businesses.

**Comment by samelamin** [comment]
I have done so yes, thankfully Databricks have updated their API and it now allows you to create clusters with env variables and that fixed the issue 

For those interested on how to do it can go (here)[https://docs.databricks.com/release-notes/product/2.30.html#set-environmental-variables-in-spark-from-rest-api]

That said I am now received this error when trying to read or write to BQ

java.lang.NoSuchMethodError: com.google.common.base.Splitter.splitToList(Ljava/lang/CharSequence;)Ljava/util/List;

and the stack trace

```
at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase$ParentTimestampUpdateIncludePredicate.create(GoogleHadoopFileSystemBase.java:572)
    at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.createOptionsBuilderFromConfig(GoogleHadoopFileSystemBase.java:1890)
    at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.configure(GoogleHadoopFileSystemBase.java:1587)
    at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:793)
    at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:756)
    at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2653)
    at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:92)
    at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2687)
    at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2669)
    at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:371)
    at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
    at com.google.cloud.hadoop.io.bigquery.AbstractBigQueryInputFormat.extractExportPathRoot(AbstractBigQueryInputFormat.java:247)
    at com.google.cloud.hadoop.io.bigquery.AbstractBigQueryInputFormat.getSplits(AbstractBigQueryInputFormat.java:107)
    at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:120)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
    at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
    at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
    at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1307)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
    at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
    at org.apache.spark.rdd.RDD.take(RDD.scala:1302)
    at org.apache.spark.rdd.RDD$$anonfun$first$1.apply(RDD.scala:1342)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
    at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
    at org.apache.spark.rdd.RDD.first(RDD.scala:1341)
    at com.spotify.spark.bigquery.package$BigQuerySQLContext.bigQueryTable(package.scala:113)
    at com.spotify.spark.bigquery.package$BigQuerySQLContext.bigQueryTable(package.scala:126)
```

A google of the error leads me to believe its Guava, Databricks spins up a cluster with version 14 while the connector is depending on version 18

I tried removing the older version when the cluster starts but that has so far failed. I think if I create a FAT jar it might fix the problem but ideally I would just want to run the code :( 

Any ideas?

**Comment by samelamin** [comment]
Finally got it to work!

Just to let you know these are the issues I faced when trying to write to Bigquery while hosting on Databricks

1) Google automatically looks for an env variables, you can now use version 2.3 of the Databricks API to launch a new cluster with Env variables. Documentation on the API can be found [here](https://docs.databricks.com/release-notes/product/2.30.html#set-environmental-variables-in-spark-from-rest-ap)

If you are too lazy here is some curl code that launches a cluster 
`%sh
curl -H "Content-Type: application/json" -X POST \
-u username:passord url-of-databricks-instance:443/api/2.0/clusters/create \
-d '
{
   "cluster_name" : "spark 161-hadoop-1",
  "spark_version": "1.6.1-ubuntu15.10-hadoop1",
   "num_workers" : 1,
   "spark_conf" : {
       "spark.speculation" : true,
       "spark.driver.userClassPathFirst" : true,
       "spark.executor.userClassPathFirst" : true
       },
       "spark_env_vars" :
           {"GOOGLE_APPLICATION_CREDENTIALS" :"/databricks/Justeat-platform-events-c750aee2059a.json"}
   }'`

2) Guava dependency conflict, the connector depends on guava 18 while the databricks environment comes with guava 14. You need to use the maven shade plugin to create a fat/uber jar and relocate the google classes

Here is my example of my maven pom
`<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>2.3</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <minimizeJar>true</minimizeJar>
          <shadedArtifactAttached>true</shadedArtifactAttached>
          <shadedClassifierName>fat</shadedClassifierName>
          <relocations>
            <relocation>
              <pattern>com.google</pattern>
              <shadedPattern>shaded.guava</shadedPattern>
              <includes>
                <include>com.google.**</include>
              </includes>

```
          <excludes>
            <exclude>com.google.common.base.Optional</exclude>
            <exclude>com.google.common.base.Absent</exclude>
            <exclude>com.google.common.base.Present</exclude>
          </excludes>
        </relocation>
      </relocations>
      <filters>
        <filter>
          <artifact>*:*</artifact>
          <excludes>
            <exclude>META-INF/*.SF</exclude>
            <exclude>META-INF/*.DSA</exclude>
            <exclude>META-INF/*.RSA</exclude>
          </excludes>
        </filter>
      </filters>
      <finalName>uber-${project.artifactId}-${project.version}</finalName>
    </configuration>
  </plugin>`
```

Thats pretty much it folks, @nevillelyh  thanks again for your amazing support!

Also if you think it might be useful, I am happy to send in a simple readme as a pr for those who are looking to work on databricks :)

**Comment by edsar** [comment]
@samelamin we're trying to do the same.  Do you have a README or something consolidated?  Thanks for breaking this ground here with BQ and Databricks!

**Comment by samelamin** [comment]
I was waiting for @nevillelyh to decide whether a readme is suitable or not, but if you follow my steps there you should be all good

I did it 7 times already to make sure it works! :D

**Comment by nevillelyh** [comment]
Hi sorry for the late response. I've been away for a while.
Feel free to submit a PR for README.md.

**Comment by samelamin** [comment]
@edsarausad FYI I forked the repoistory to make it easier to work with Databricks, feel free to check it [out](https://github.com/samelamin/spark-bigquery/)

Feedback is always welcome

**Comment by kurtmaile** [comment]
Cool will take a look at this!  How tested is the structured streaming integration?  Do you think its production ready?

Cheers!

**Comment by samelamin** [comment]
Well we are using the structured streaming for non crucial features so it'd
pretty reliable. That said the spark code underneath is still alpha so I
wouldn't put it over things that are crucial to your pipeline!

Not till spark takes it outside alpha

But the main issues Ive faced with it is that structured streaming was
meant to unify the batch and streaming processes but some of the api
functionality doesn't work on streaming compared to batch.e.g.
dropDuplicates. But these are routinely picked up and fixed. So the age old
answer of it depends applies here

**Comment by kurtmaile** [comment]
Cool thanks for the speedy response will feed back any comments as I use it.  Much appreciated
