### ISSUE TITLE
Unable to get a sqlContext

### ISSUE THREAD

**Issue by michaelsmithhx** [spotify/spark-bigquery#18]
I don't have a sqlContext when I fire up the spark shell as instructed. I also encounter the following error, is this a permissions/firewall issue?

```
16/10/24 14:53:31 WARN org.apache.hadoop.hdfs.DFSClient: Caught exception 
java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.Thread.join(Thread.java:1245)
        at java.lang.Thread.join(Thread.java:1319)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.closeResponder(DFSOutputStream.java:609)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.endBlock(DFSOutputStream.java:370)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:546)
```

(I get 5 of these on startup)

Thanks,
Mike S

**Comment by nevillelyh** [comment]
That's from HDFS client not sure how relevant to this package. Does that happen without the `spark-bigquery` package?

**Comment by konurbaev-e** [comment]
You can ignore this exception:
http://stackoverflow.com/questions/39351690/got-interruptedexception-while-executing-word-count-mapreduce-job/
