### ISSUE TITLE
IoException with bigQuerySelect

### ISSUE THREAD

**Issue by jgustave** [spotify/spark-bigquery#55]
For some reason I get an IOException when I use bigQuerySelect(). However starting with bigQueryTable() and doing the equivalent select works fine. I tried multiple tables.

Using 0.2.2-s_2.11

```

17/12/20 21:15:05 ERROR ApplicationMaster: User class threw exception: java.util.concurrent.ExecutionException: java.io.IOException: Encountered " "-" "- "" at line 1, column 20.
Was expecting:
    <EOF> 
    
java.util.concurrent.ExecutionException: java.io.IOException: Encountered " "-" "- "" at line 1, column 20.
Was expecting:
    <EOF> 
    
	at shaded_guavaz.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
	at shaded_guavaz.util.concurrent.AbstractFuture.get(AbstractFuture.java:459)
	at shaded_guavaz.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:76)
	at shaded_guavaz.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:142)
	at shaded_guavaz.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2373)
	at shaded_guavaz.cache.LocalCache$Segment.loadSync(LocalCache.java:2337)
	at shaded_guavaz.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
	at shaded_guavaz.cache.LocalCache$Segment.get(LocalCache.java:2208)
	at shaded_guavaz.cache.LocalCache.get(LocalCache.java:4053)
	at shaded_guavaz.cache.LocalCache.getOrLoad(LocalCache.java:4057)
	at shaded_guavaz.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
	at com.spotify.spark.bigquery.BigQueryClient.query(BigQueryClient.scala:105)
	at com.spotify.spark.bigquery.BigQuerySQLContext.bigQuerySelect(BigQuerySQLContext.scala:93)
	at com.zulily.utils.data.BqTest$.foo(BqTest.scala:186)
	at com.zulily.utils.data.BqTest$.main(BqTest.scala:46)
	at com.zulily.utils.data.BqTest.main(BqTest.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:637)
Caused by: java.io.IOException: Encountered " "-" "- "" at line 1, column 20.
Was expecting:
    <EOF> 
    
	at com.google.cloud.hadoop.io.bigquery.BigQueryUtils.waitForJobCompletion(BigQueryUtils.java:95)
	at com.spotify.spark.bigquery.BigQueryClient.com$spotify$spark$bigquery$BigQueryClient$$waitForJob(BigQueryClient.scala:134)
	at com.spotify.spark.bigquery.BigQueryClient$$anon$1.load(BigQueryClient.scala:90)
	at com.spotify.spark.bigquery.BigQueryClient$$anon$1.load(BigQueryClient.scala:79)
	at shaded_guavaz.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
	at shaded_guavaz.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
	... 15 more

```

**Comment by yanasega** [comment]
verify that the string representing the table in your query look like this: [" +PROJECT_NAME + ":" + DATASET_NAME + "." + TABLE_NAME + "]

**Comment by murakamiyuki** [comment]
That way, I succeeded
```
SELECT
  *
FROM
  [PROJECT_NAME:DATASET_NAME.TABLE_NAME]
```
